apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-app
  template:
    metadata:
      labels:
        app: db-app
    spec:
      containers:
      - name: db-container
        image: bhavenp/cs207-lecture25:db
        imagePullPolicy: Always
        ports:
        - containerPort: 8081