 # building our own Docker image.
 FROM ubuntu:latest
 RUN apt-get update 

 # The following line will copy the apollo13.txt file to the Docker container 
 # using the path that is specified second.
 COPY apollo13.txt /apollo13.txt